### ISSUE TITLE
Angular Translate integration for the Input

### ISSUE THREAD

**Issue by mesosteros** [brexis/angular-js-xlsx#11]
We are using the library successfully, the only thing is that we can't seem to implement angular-translate so that we can change the input's language to match what the user has selected as his language, instead of letting the browser language do that (which is unwanted in our project: the user must be able to make his own selection).
How can we add the translate filter to the js-xls input (and also change the layout for the input button to be a bootstrap button for that matter)? We've only found the input itself as is below in your files as well as the js-xslx library.
`<js-xlsx onread="read" onerror="error"></js-xlsx>`

**Comment by mesosteros** [comment]
The issue was actually from how to style an input with type file, not the libraries themselves. By wrapping in a label and making the input have the property "display: none;" we achieved the desired result.

**Comment by SheetJSDev** [comment]
@mesosteros does it make sense to add that to the directive?

**Comment by mesosteros** [comment]
@SheetJSDev Not really, it is simple. I think anyone can understand it from my answer above so all they need to do is search the issues.
